var country_codes = [
["at", "AUT", "Austria"],
["be", "BEL", "Belgium"],
["bg", "BGR", "Bulgaria"],
["hr", "HRV", "Croatia"],
["cy", "CYP", "Cyprus"],
["cz", "CZE", "Czech Republic"],
["dk", "DNK", "Denmark"],
["ee", "EST", "Estonia"],
["fi", "FIN", "Finland"],
["fr", "FRA", "France"],
["de", "DEU", "Germany"],
["gr", "GRC", "Greece"],
["hu", "HUN", "Hungary"],
["ie", "IRL", "Ireland"],
["it", "ITA", "Italy"],
["lv", "LVA", "Latvia"],
["lt", "LTU", "Lithuania"],
["lu", "LUX", "Luxembourg"],
["mt", "MLT", "Malta"],
["nl", "NLD", "Netherlands"],
["no", "NOR", "Norway"],
["pl", "POL", "Poland"],
["pt", "PRT", "Portugal"],
["ro", "ROU", "Romania"],
["sk", "SVK", "Slovakia"],
["si", "SVN", "Slovenia"],
["es", "ESP", "Spain"],
["se", "SWE", "Sweden"],
["tr", "TUR", "Turkey"],
["gb", "GBR", "United Kingdom"]];